---
kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules

  - name: dependencies
    image: node
    failure: ignore
    commands:
      - npm ci
    depends_on:
      - restore-cache

  - name: lint
    image: node
    commands:
      - npm run lint
    depends_on:
      - dependencies

  - name: build
    image: node
    commands:
      - npm run build
    environment:
      VITE_SUBPATH: /tghandbook/${DRONE_COMMIT_BRANCH/\//_}-${DRONE_COMMIT_SHA:0:8}
      VITE_APP_REVISION: ${DRONE_COMMIT_SHA}
    when:
      event:
        include:
          - push
          - pull_request
    depends_on:
      - dependencies

  - name: upload_build_versioned
    image: plugins/s3
    settings:
      bucket: tghandbook
      access_key:
        from_secret: minio_access
      secret_key:
        from_secret: minio_secret
      source: dist/**/*
      target: /${DRONE_COMMIT_BRANCH/\//_}-${DRONE_COMMIT_SHA:0:8}/
      strip_prefix: dist/
      path_style: true
      endpoint: https://artifacts.fromouter.space
    when:
      event:
        - push
    depends_on:
      - build

  - name: upload_build_pr
    image: plugins/s3
    settings:
      bucket: tghandbook
      access_key:
        from_secret: minio_access
      secret_key:
        from_secret: minio_secret
      source: dist/**/*
      target: /pr-${DRONE_PULL_REQUEST}/
      strip_prefix: dist/
      path_style: true
      endpoint: https://artifacts.fromouter.space
    when:
      event:
        - pull_request
    depends_on:
      - build

  - name: upload_build_branch
    image: plugins/s3
    settings:
      bucket: tghandbook
      access_key:
        from_secret: minio_access
      secret_key:
        from_secret: minio_secret
      source: dist/**/*
      target: /${DRONE_COMMIT_BRANCH/\//_}/
      strip_prefix: dist/
      path_style: true
      endpoint: https://artifacts.fromouter.space
    when:
      event:
        - push
    depends_on:
      - build

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    failure: ignore
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
    depends_on:
      - dependencies

volumes:
  - name: cache
    host:
      path: /opt/gitea/drone-cache/hamcha/tghandbook

trigger:
  event:
    - push
    - pull_request
---
kind: signature
hmac: 80f0ae9213a4857606e7a6f2e64b9f1f47f1b80186f9ecd5b7aada7481a75db4
